### ISSUE TITLE
no picture

### ISSUE THREAD

**Issue by CPernet** [openneuropet/brainhack#1]
I'm not sure if it's the automated rendering or the config, but the picture doesn't seem to load (on the website) -- tried at root loc or within images/

**Comment by CPernet** [comment]
tried mkd style, now html style to call the image :-(

**Comment by CPernet** [comment]
note it would be useful to be able to do that so we can add our funders

**Comment by pwighton** [comment]
[Stackoverflow saves the day](https://stackoverflow.com/questions/17141612/images-in-github-pages-and-relative-links)!

> If you're trying to link from your GitHub Pages to an image in your main repo, you need to use the "raw" absolutely link. You can get that by going to the image in the main repo, clicking on raw and then copying that
